source "https://rubygems.org"

ruby "3.4.5"

gem "pg", ">= 1.6"
gem "pliny", ">= 1"
gem "pry"
gem "puma", ">= 7"
gem "rack-ssl"
gem "rack-timeout"
gem "rake"
gem "rollbar"
gem "sequel", ">= 5"
gem "sequel-paranoid"
gem "sequel_pg", require: "sequel"
gem "sinatra", ">= 4", require: "sinatra/base"
gem "sinatra-contrib", require: ["sinatra/namespace", "sinatra/reloader"]
gem "sinatra-router"
gem "sucker_punch"

group :development, :test do
  gem "pry-byebug"
  gem "rubocop", require: false
  gem "rubocop-rspec", require: false
end

group :test do
  gem "committee"
  gem "database_cleaner"
  gem "dotenv"
  gem "rack-test"
  gem "rspec"
  gem "simplecov", require: false
end
