# frozen_string_literal: true

# create Endpoints::Base so we can test subclasses generated by Pliny:
module Endpoints
  class Base < Sinatra::Base
    register Sinatra::Namespace
    helpers Pliny::Helpers::Encode
    helpers Pliny::Helpers::Params
  end
end
